# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: meenaaraj/app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9090  # Changed to port 9090

